### ISSUE TITLE
Clicking on a card to expand it causes it to crash

### ISSUE THREAD

**Issue by wooldridgetm** [Ekalips/ExpandableCardViewList#1]
When I tried to expand one of the cards...the app crashed.

running 
- Android Studio 2.3
- Android 7.1.1, Nexus 6P emulator 

**Logcat...**

<img width="1824" alt="screen shot 2017-03-10 at 5 24 24 pm" src="https://cloud.githubusercontent.com/assets/13317009/23815475/6ed51cfa-05b6-11e7-9764-c9ae345f5112.png">

```
03-10 17:17:53.930 7484-7484/com.wldev.expandablecardviewlist D/Bindings: animate: 
03-10 17:17:53.931 7484-7484/com.wldev.expandablecardviewlist D/AndroidRuntime: Shutting down VM
03-10 17:17:53.935 7484-7484/com.wldev.expandablecardviewlist E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.wldev.expandablecardviewlist, PID: 7484

 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
      at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.createRTAnimator(AnimatedVectorDrawable.java:1262)
      at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.parseAnimatorSet(AnimatedVectorDrawable.java:1220)
      at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.init(AnimatedVectorDrawable.java:1187)
      at android.graphics.drawable.AnimatedVectorDrawable.ensureAnimatorSet(AnimatedVectorDrawable.java:851)
      at android.graphics.drawable.AnimatedVectorDrawable.start(AnimatedVectorDrawable.java:834)
      at com.wldev.expandablecardviewlist.Bindings.animate(Bindings.java:111)
      at com.wldev.expandablecardviewlist.databinding.RvItemBinding.executeBindings(RvItemBinding.java:294)
      at android.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:379)
      at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:351)
      at android.databinding.ViewDataBinding$6.run(ViewDataBinding.java:178)
      at android.databinding.ViewDataBinding$7.doFrame(ViewDataBinding.java:251)
      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
      at android.view.Choreographer.doCallbacks(Choreographer.java:686)
      at android.view.Choreographer.doFrame(Choreographer.java:618)
      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
      at android.os.Handler.handleCallback(Handler.java:751)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6119)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)


```

**Comment by Ekalips** [comment]
Does this issue reproduces on pre-marshmallow emulator/device?

**Comment by wooldridgetm** [comment]
it works fine on Lollipop.  

Interesting, I wouldn't have guessed that b/c targetSdk=25.  Good catch.
